app = "myproject-purple-river-37"
primary_region = "sjc"

[build]
  # …기존 빌드 설정…

# FastAPI가 0.0.0.0:8080에서 HTTP 서비스만 쓰도록 하는 설정입니다.
[http_service]
  internal_port       = 8080
  force_https         = true
  auto_stop_machines  = "stop"
  auto_start_machines = true
  min_machines_running = 0

# services 블록을 남겨두되, v2 형식에 맞춰 수정합니다.
[[services]]
  internal_port = 8080
  # protocol → protocols, 리스트 형태로 변경
  protocols     = ["tcp"]
  ports = [
    # HTTP 핸들러 지정
    { port = 80,  handlers = ["http"] },
    { port = 443, handlers = ["http"] },
  ]

# (원한다면) 헬스체크를 직접 services 블록에 넣을 수도 있습니다.
[[services.http_checks]]
  interval        = "10s"
  grace_period    = "5s"
  timeout         = "2s"
  method          = "get"
  path            = "/health"
  tls_skip_verify = false
