app = "myproject-purple-river-37"
primary_region = "sjc"

[build]
  # (필요한 경우 여기에 빌드 설정 추가)

[processes]
  app = "python main.py"

[[services]]
  processes     = ["app"]
  protocol      = "tcp"
  internal_port = 8080

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  [[services.checks]]
    type         = "http"
    protocol     = "http"
    port         = 8080
    path         = "/health"
    interval     = "10s"
    timeout      = "2s"
    grace_period = "5s"
