[binance]
API_KEY    = "0Iy5hnS85PG8z1SUhxLeeJSPqMxZinSlSXURFBp7NnhGTdwgcNrLsT2LkMIEzAh8"
SECRET_KEY = "0Z51MHECINDRFKTxcfd0sy8eHg9f8ffvWwxUPD5wCoZJT1sUXD2iEz8lqF2DZsRq"

[telegram]
TOKEN    = "7711067916:AAEGzlvDlFkaOIeMu79MyqFLtKbvIe6ut"
CHAT_ID  = "7723917285"
